apiVersion: v1
kind: Service
metadata:
  name: monitoring-dashboard
spec:
  type: NodePort
  selector:
    app: monitoring-dashboard
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30007

